jobs:
  build:
    working_directory: ~/rozkroje
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build client app
          command: npm run client:build
      - run: 
          name: Run Tests
          command: npm run test

# branches:
#   only:
#     - master

# deployment:
#   production:
#     branch: master
#     heroku:
#       appname: rozkroje
#     commands:
#       - |
#         cat >~/.netrc <<EOF
#         machine api.heroku.com
#           login $HEROKU_EMAIL
#           password $HEROKU_TOKEN
#         machine git.heroku.com
#           login $HEROKU_EMAIL
#           password $HEROKU_TOKEN
#         EOF
#       - chmod 600 ~/.netrc # Heroku cli complains about permissions without this
#       - "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"
#       - git push git@heroku.com:rozkroje.git $CIRCLE_SHA1:refs/heads/master