jobs:
  build:
    working_directory: ~/rozkroje
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build client app
          command: npm run client:build
      - run: 
          name: Run Tests
          command: npm run test