jobs:
  build:
    docker:
      - image: circleci/node:7
    working_directory: ~/
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm install
      - run: npm run client:build

workflows:
  version: 1
  build_app:
    jobs:
      - build

branches:
  only:
    - new-app