jobs:
  build:
    working_directory: ~/rozkroje
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: 'Information'
          command: node -v | npm -v
      - run: npm install
      - run: npm run client:build

branches:
  only:
    - new-app