jobs:
  build:
    working_directory: ~/rozkroje
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: npm install
      - run: npm run client:build

branches:
  only:
    - new-app